apps/workspaces/urls.py
from django.urls import path
from apps.workspaces.views import (
    get_workspaces_view,
    create_workspace_view,
    edit_workspace_view,
    delete_workspace_view,
    add_team_to_workspace_view,
    get_workspace_teams_view,
    remove_team_from_workspace_view,
    change_workspace_team_remittance_rate_view,
    WorkspaceExchangeRateListView,
    WorkspaceExchangeRateCreateView,
    WorkspaceExchangeRateUpdateView,
    WorkspaceExchangeRateDetailView,
    WorkspaceExchangeRateDeleteView,
)

urlpatterns = [
    path("", get_workspaces_view, name="workspace_list"),
    path("create/", create_workspace_view, name="create_workspace"),
    path("edit/<uuid:workspace_id>/", edit_workspace_view, name="edit_workspace"),
    path("delete/<uuid:workspace_id>/", delete_workspace_view, name="delete_workspace"),
    path(
        "add-team/<uuid:workspace_id>/",
        add_team_to_workspace_view,
        name="add_team_to_workspace",
    ),
    path(
        "<uuid:workspace_id>/teams/",
        get_workspace_teams_view,
        name="get_workspace_teams",
    ),
    path(
        "<uuid:workspace_id>/teams/<uuid:team_id>/remove/",
        remove_team_from_workspace_view,
        name="remove_team_from_workspace",
    ),
    path(
        "<uuid:workspace_id>/teams/<uuid:team_id>/remittance/<uuid:workspace_team_id>/",
        change_workspace_team_remittance_rate_view,
        name="change_workspace_team_remittance_rate",
    ),
    path(
        "<uuid:workspace_id>/exchange-rates/",
        WorkspaceExchangeRateListView.as_view(),
        name="workspace_exchange_rate_list",
    ),
    path(
        "<uuid:workspace_id>/exchange-rates/create/",
        WorkspaceExchangeRateCreateView.as_view(),
        name="workspace_exchange_rate_create",
    ),
    path(
        "<uuid:workspace_id>/exchange-rates/<uuid:pk>/edit/",
        WorkspaceExchangeRateUpdateView.as_view(),
        name="workspace_exchange_rate_update",
    ),
    path(
        "<uuid:workspace_id>/exchange-rates/<uuid:pk>/detail/",
        WorkspaceExchangeRateDetailView.as_view(),
        name="workspace_exchange_rate_detail",
    ),
    path(
        "<uuid:workspace_id>/exchange-rates/<uuid:pk>/delete/",
        WorkspaceExchangeRateDeleteView.as_view(),
        name="workspace_exchange_rate_delete",
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.organizations.urls")),
    path("", include("apps.core.urls")),
    path("accounts/", include("allauth.urls")),
    path("<uuid:organization_id>/auditlog/", include("apps.auditlog.urls")),
    path("<uuid:organization_id>/workspaces/", include("apps.workspaces.urls")),
    path("<uuid:organization_id>/", include("apps.workspaces.custom_urls")),
    path("invitations/", include("apps.invitations.urls")),
    path("<uuid:organization_id>/teams/", include("apps.teams.urls")),
    path("<uuid:organization_id>/remittances/", include("apps.remittance.urls")),
    path("<uuid:organization_id>/", include("apps.entries.urls")),
    path("<uuid:organization_id>/", include("apps.reports.urls")),
    path("attachments/", include("apps.attachments.urls")),
]

if settings.DEBUG:
    from debug_toolbar.toolbar import debug_toolbar_urls

    urlpatterns += debug_toolbar_urls()

apps/workspaces/models.py
import uuid
from decimal import Decimal

from django.db import models
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator

from apps.core.models import SoftDeleteModel, baseModel
from apps.organizations.models import Organization, OrganizationMember
from apps.workspaces.constants import StatusChoices
from apps.teams.models import Team
from apps.currencies.models import ExchangeRateBaseModel
from apps.core.permissions import WorkspacePermissions, WorkspaceTeamPermissions


# Create your models here.
class Workspace(baseModel):
    workspace_id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False
    )
    organization = models.ForeignKey(
        Organization, on_delete=models.CASCADE, related_name="workspaces"
    )
    workspace_admin = models.ForeignKey(
        OrganizationMember,
        on_delete=models.SET_NULL,
        related_name="administered_workspaces",
        null=True,
        blank=True,
    )  # This is the workspace admin of the workspace, it can be null if the workspace is not yet administered and will be assigned later.
    operations_reviewer = models.ForeignKey(
        OrganizationMember,
        on_delete=models.SET_NULL,
        related_name="reviewed_workspaces",
        null=True,
        blank=True,
    )  # This is the operation reviewer of the workspace, it can be null if the workspace is not yet reviewed and will be assigned later.
    title = models.CharField(max_length=255, null=False, blank=False)
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(
        OrganizationMember,
        on_delete=models.SET_NULL,
        null=True,
        related_name="created_workspaces",
    )
    status = models.CharField(
        max_length=20,
        choices=StatusChoices.choices,
        default=StatusChoices.ACTIVE,
    )
    remittance_rate = models.DecimalField(
        max_digits=5,  # 0.00 - 100.00
        decimal_places=2,
        default=90.00,
        help_text="% obligation from entries (Default 90%)",
        validators=[
            MinValueValidator(Decimal("0.00")),
            MaxValueValidator(Decimal("100.00")),
        ],
    )
    start_date = models.DateField()
    end_date = models.DateField()

    class Meta:
        verbose_name = "workspace"
        verbose_name_plural = "workspaces"
        ordering = ["-created_at"]
        permissions = (
            (
                WorkspacePermissions.ASSIGN_TEAMS,
                WorkspacePermissions.ASSIGN_TEAMS.label,
            ),
            (
                WorkspacePermissions.ADD_WORKSPACE_ENTRY,
                WorkspacePermissions.ADD_WORKSPACE_ENTRY.label,
            ),
            (
                WorkspacePermissions.CHANGE_WORKSPACE_ENTRY,
                WorkspacePermissions.CHANGE_WORKSPACE_ENTRY.label,
            ),
            (
                WorkspacePermissions.DELETE_WORKSPACE_ENTRY,
                WorkspacePermissions.DELETE_WORKSPACE_ENTRY.label,
            ),
            (
                WorkspacePermissions.VIEW_WORKSPACE_ENTRY,
                WorkspacePermissions.VIEW_WORKSPACE_ENTRY.label,
            ),
            (
                WorkspacePermissions.VIEW_WORKSPACE_TEAMS_UNDER_WORKSPACE,
                WorkspacePermissions.VIEW_WORKSPACE_TEAMS_UNDER_WORKSPACE.label,
            ),
            (
                WorkspacePermissions.ADD_WORKSPACE_CURRENCY,
                WorkspacePermissions.ADD_WORKSPACE_CURRENCY.label,
            ),
            (
                WorkspacePermissions.CHANGE_WORKSPACE_CURRENCY,
                WorkspacePermissions.CHANGE_WORKSPACE_CURRENCY.label,
            ),
            (
                WorkspacePermissions.DELETE_WORKSPACE_CURRENCY,
                WorkspacePermissions.DELETE_WORKSPACE_CURRENCY.label,
            ),
            (
                WorkspacePermissions.VIEW_WORKSPACE_CURRENCY,
                WorkspacePermissions.VIEW_WORKSPACE_CURRENCY.label,
            ),
            (
                WorkspacePermissions.VIEW_TOTAL_WORKSPACE_TEAMS_ENTRIES,
                WorkspacePermissions.VIEW_TOTAL_WORKSPACE_TEAMS_ENTRIES.label,
            ),
        )
        constraints = [
            models.UniqueConstraint(
                fields=["organization", "title"],
                name="unique_workspace_in_organization",
            )
        ]

    def clean(self):
        if self.start_date > self.end_date:
            raise ValidationError("Start date must be before end date.")

    def __str__(self):
        return f"{self.title} ({self.organization.title})"


class WorkspaceTeam(baseModel):
    workspace_team_id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False
    )
    team = models.ForeignKey(
        Team, on_delete=models.CASCADE, related_name="joined_workspaces"
    )
    workspace = models.ForeignKey(
        Workspace, on_delete=models.CASCADE, related_name="joined_teams"
    )
    syned_with_workspace_remittance_rate = models.BooleanField(
        default=True
    )  # if True, the custom remittance rate will be ignored
    custom_remittance_rate = models.DecimalField(
        max_digits=5,  # 0.00 - 100.00
        decimal_places=2,
        null=True,
        blank=True,
        validators=[
            MinValueValidator(Decimal("0.00")),
            MaxValueValidator(Decimal("100.00")),
        ],
        help_text="the custom remittance rate will ignore the workspace default remittance rate",
    )

    class Meta:
        verbose_name = "workspace team"
        verbose_name_plural = "workspace teams"
        ordering = ["-created_at"]
        permissions = (
            (
                WorkspaceTeamPermissions.VIEW_WORKSPACE_TEAM,
                WorkspaceTeamPermissions.VIEW_WORKSPACE_TEAM.label,
            ),
            (
                WorkspaceTeamPermissions.ADD_WORKSPACE_TEAM_ENTRY,
                WorkspaceTeamPermissions.ADD_WORKSPACE_TEAM_ENTRY.label,
            ),
            (
                WorkspaceTeamPermissions.CHANGE_WORKSPACE_TEAM_ENTRY,
                WorkspaceTeamPermissions.CHANGE_WORKSPACE_TEAM_ENTRY.label,
            ),
            (
                WorkspaceTeamPermissions.DELETE_WORKSPACE_TEAM_ENTRY,
                WorkspaceTeamPermissions.DELETE_WORKSPACE_TEAM_ENTRY.label,
            ),
        )
        constraints = [
            models.UniqueConstraint(
                fields=["team", "workspace"], name="unique_team_in_workspace"
            )
        ]

    def __str__(self):
        return f"{self.team.title} in {self.workspace.title}"


class WorkspaceExchangeRate(ExchangeRateBaseModel, SoftDeleteModel):
    workspace_exchange_rate_id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False
    )
    is_approved = models.BooleanField(default=False)
    approved_by = models.ForeignKey(
        OrganizationMember,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="%(app_label)s_approved_%(class)s_set",
    )
    workspace = models.ForeignKey(
        Workspace,
        on_delete=models.CASCADE,
        related_name="workspace_exchange_rates",
    )

    class Meta:
        verbose_name = "Workspace Exchange Rate"
        verbose_name_plural = "Workspace Exchange Rates"
        constraints = [
            models.UniqueConstraint(
                fields=["workspace", "currency", "effective_date"],
                condition=models.Q(deleted_at__isnull=True),
                name="unique_workspace_exchange_rate",
            )
        ]

apps/workspaces/templates/workspaces/index.html
{% extends "layouts/organization_layout.html" %}


{% block header %}
    {% include "components/organization_layout_header.html" with title="Workspaces" subtitle="Manage your project workspaces" %}
{% endblock %}

{% block content %}
  {% include "workspaces/main_content.html" %}
{% endblock %}

apps/workspaces/templates/workspaces/main_content.html
<div class="container mx-auto px-4 py-8">
    <div class="flex justify-between items-center mb-8">
        <div>
            <h1 class="text-3xl font-bold">My Workspaces under {{ organization.title }} Organization</h1>
            <p class="text-base-content/70 mt-2">Manage your project workspaces</p>
        </div>
  
        <a 
            hx-get="{% url 'create_workspace' organization_id=request.resolver_match.kwargs.organization_id %}" 
            hx-target="#modal-placeholder" 
            hx-swap="innerHTML" 
            class="btn btn-primary btn-soft shadow hover:text-white"
        >
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
            </svg>
            New Workspace
        </a>
        
    </div>
   
    {% include "workspaces/partials/workspaces_grid.html" %}
    <!-- Modal for workspace creation -->
    <!-- <div id="workspace-create-modal"></div>
    <div id="workspace-edit-modal"></div> -->
</div>

apps/workspaces/templates/workspaces/workspace_form.html
<div x-data="{ open: true }" x-show="open" @keydown.escape.window="open = false">
 
    <div class="modal modal-open">
 
        {% include "includes/message.html" %}

      <form 
            class="modal-box max-w-lg bg-white shadow-xl rounded-lg" 
            @click.outside="open = false"
            hx-post="{% url 'create_workspace' organization_id=request.resolver_match.kwargs.organization_id %}"
            hx-target="#workspace-form-modal"
            hx-swap="innerHTML">
        {% csrf_token %}
        <input type="hidden" name="organization_id" value="{{ request.resolver_match.kwargs.organization_id }}">
        <div class="p-8">
          <h2 class="text-2xl font-bold text-gray-800 mb-8">Create Workspace in {{ organization.title }}</h2>

          <div id="form-errors" class="mb-4">
            {% if form.non_field_errors %}
              <div class="bg-red-50 border-l-4 border-red-400 p-4 rounded-lg">
                <div class="flex items-center">
                  <div class="flex-shrink-0">
                    <svg class="h-5 w-5 text-red-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                      <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
                    </svg>
                  </div>
                  <div class="ml-3">
                    <p class="text-sm text-red-700">
                      {{ form.non_field_errors|join:", " }}
                    </p>
                  </div>
                </div>
              </div>
            {% endif %}
          </div>

          <div class="mb-6">
            <label for="id_title" class="block text-lg font-medium text-gray-700 mb-2">Title</label>
            {{ form.title.errors }}
            {{ form.title }}
          </div>

          <div class="mb-6">
            <label for="id_description" class="block text-lg font-medium text-gray-700 mb-2">Description</label>
            {{ form.description.errors }}
            {{ form.description }}
          </div>

          <div class="mb-6">
            <label for="id_remittance_rate" class="block text-lg font-medium text-gray-700 mb-2">Remittance Rate (%)</label>
            {{ form.remittance_rate.errors }}
            {{ form.remittance_rate }}
          </div>

          <div class="mb-6">
            <label for="id_start_date" class="block text-lg font-medium text-gray-700 mb-2">Start Date</label>
            {{ form.start_date.errors }}
            {{ form.start_date }}
          </div>

          <div class="mb-6">
            <label for="id_end_date" class="block text-lg font-medium text-gray-700 mb-2">End Date (Optional)</label>
            {{ form.end_date.errors }}
            {{ form.end_date }}
          </div>

          <div class="mb-8">
            <label for="id_status" class="block text-lg font-medium text-gray-700 mb-2">Status</label>
            {{ form.status.errors }}
            {{ form.status }}
          </div>

          <div class="mb-8">
            <label for="id_workspace_admin" class="block text-lg font-medium text-gray-700 mb-2">Workspace Admin</label>
            {{ form.workspace_admin.errors }}
            {{ form.workspace_admin }}
          </div>

          <div class="flex justify-end space-x-3">
            <button type="button" class="btn btn-base w-full sm:w-auto" @click="open = false">
              Cancel
            </button>
            <button type="submit" class="btn btn-primary w-full sm:w-auto">
              Create Workspace
            </button>
          </div>
        </div>
      </form>
  
      <!-- background click to close the modal temporariy commented due to low perfomance( figure out later ) -->
      <!-- <div class="modal-backdrop bg-black/50 backdrop-blur-sm" @click="open = false"></div> -->
    </div>
  </div>
  

apps/workspaces/templates/workspaces/workspace_teams.html
{% block header %}
   
    {% include "components/organization_layout_header.html" with title="Workspace Teams" subtitle="Manage your Team Under a Workspace" %}
{% endblock %}

<div class="divider my-0 mb-5"></div>

{% block content %}
  <div id="workspace-teams-container">
  {% include "workspaces/partials/workspaces_team_display.html" %}
  </div>
{% endblock %}


apps/workspaces/templates/workspaces/workspace_teams_main.html
{% extends "layouts/custom_workspace_teams_layout.html" %}

{% block secondary_content %}
  {% include "workspaces/partials/workspaces_team_display.html" %}
{% endblock %}